<?php

require __DIR__ . "/../loader.php";

use AI\Agents\Zabbix\{ZabbixAutoScreening, ZabbixScanner, ZabbixHostFinderAgent};
use AI\Agents\Itsm\ItsmIncidentManager;
use NeuronAI\Chat\Messages\{UserMessage, Stream\Chunks\TextChunk};
use ServiceNOW\Client as ServiceNOW;

try {
    global $db_dat;

    $lockFile = fopen(__DIR__ .'/run.lock', 'c');

    if (!flock($lockFile, LOCK_EX | LOCK_NB)) {
        exit("Script is already running...\n\n");
    }

    $snow = new ServiceNOW(instance: SERVICENOW_INSTANCE_CUSTOM_URL, authentication_type: "basic", authentication_data: ['username' => SERVICENOW_INSTANCE_USER, "password" => SERVICENOW_INSTANCE_PASSWORD], proxy: PROXY, secure: false, custom_url: true);

    $incident = $snow->RetrieveRecord(table: "incident", number: "INC09735410");

    if(!$incident['status']){
        throw new \Exception("Error fetching record: ". $incident['Message']);
    }
    
    $number = $incident['data'][0]['number'];

    $outputFile = __DIR__ . "/tmp/{$number}_screening_" . date('YmdHis') . ".txt";

    echo "--- Fetching Incident: $number ---\n";
    $getIncident = ItsmIncidentManager::make()->stream(new UserMessage("Show me a summary of incident $number"));
    $incidentData = "";
    foreach ($getIncident->events() as $chunk) {
        if ($chunk instanceof TextChunk) {
            $incidentData .= $chunk->content;
        }
    }

    echo $incidentData . "\n\n";

    // 1.1 Find Zabbix Hosts
    echo "--- Finding Zabbix Hosts ---\n";
    $hostFinder = ZabbixHostFinderAgent::make()
        ->chat(new UserMessage("Find Zabbix hostIds in this incident: $incidentData"))
        ->getMessage()->getContent();

    $hostData = json_decode($hostFinder, true);
    $hostIds = [];
    if (isset($hostData['hosts'])) {
        foreach ($hostData['hosts'] as $h) {
            $hostIds[$h['hostid']] = $h['operating_system'];
        }
    }

    if (empty($hostIds)) {
        die("No Zabbix hosts found for this incident. Skipping scan.\n");
        // Update status to processed but with warning/no-hosts
    }

    echo "Found Host IDs: " . implode(", ", array_keys($hostIds)) . "\n\n";

    $incidentData .= "Operating System per hostId:\n";
    foreach($hostIds as $id => $os){
        $incidentData .= $id . ': '. $os . "\n";
    }

    // 2. Screening
    echo "--- Screening for Commands ---\n";
    $screeningResult = ZabbixAutoScreening::make()
        ->chat(new UserMessage("Make a triage for this incident: $incidentData"))
        ->getMessage()->getContent();

    $screeningJson = json_decode($screeningResult, true);
    $screeningJson['hostIds'] = $hostIds; // Inject hostIds found
    $screening = json_encode($screeningJson);

    echo $screening . "\n\n";

    // 3. Execution
    echo "--- Running Zabbix Scan ---\n";
    $scanner = ZabbixScanner::make()
        ->stream(new UserMessage("According to the following JSON, run the commands in the servers: $screening"));

    $zabbixData = "";
    foreach ($scanner->events() as $chunk) {
        if ($chunk instanceof TextChunk) {
            echo $chunk->content;
            $zabbixData .= $chunk->content;
            file_put_contents($outputFile, $chunk->content, FILE_APPEND);
        }
    }

    $screening_output = $itsm_output = "";

    if (preg_match("/0- STATUS RESULT:\\s*\\n\\s*(.+)/i", $zabbixData, $matches))
    {
        $linha = trim($matches[1]);
        $screening_output = $linha;
    }

    $screening_output = $screening_output . "\n\n" . $zabbixData . "\n\n";

    $itsm_output = "AI Agent:"  . "\n\n"
        . $zabbixData  . "\n\n"
        . "THIS MESSAGE WAS GENERATED BY AN AUTONOMOUS AI-AGENT, WHICH IS CURRENTLY IN TEST STAGE\n"
        . "USERS ARE ADVISED TO CHECK ALL PROVIDED INFORMATION BEFORE TAKING ANY ACTION BASED ON PROVIDED INFO";

} catch (\Throwable $e) {
    echo "Error: " . $e->getMessage() . "\n";
}