<?php

declare(strict_types=1);

namespace AI\Core\Formatters;

use AI\Core\DTO\ScannerResult;

final class ServiceNowFormatter implements FormatterInterface
{
    public function __construct(
        private readonly ConsoleFormatter $consoleFormatter = new ConsoleFormatter()
    ) {
    }

    public function format(ScannerResult $result): string
    {
        return "AI Agent:\n\n"
            . $this->consoleFormatter->format($result) . "\n\n"
            . "THIS MESSAGE WAS GENERATED BY AN AUTONOMOUS AI-AGENT, WHICH IS CURRENTLY IN TEST STAGE\n"
            . "USERS ARE ADVISED TO CHECK ALL PROVIDED INFORMATION BEFORE TAKING ANY ACTION BASED ON PROVIDED INFO";
    }
}
