<?php

namespace AI\Core\Errors;

enum ZabbixErrorCode: string
{
    case SCRIPT_CREATION_FAILED = 'ZBX_SCRIPT_CREATION_FAILED';
    case SCRIPT_EXECUTION_FAILED = 'ZBX_SCRIPT_EXECUTION_FAILED';
    case SCRIPT_CLEANUP_FAILED = 'ZBX_SCRIPT_CLEANUP_FAILED';
    case CLIENT_INITIALIZATION_FAILED = 'ZBX_CLIENT_INITIALIZATION_FAILED';
    case INVALID_EXECUTION_TYPE = 'ZBX_INVALID_EXECUTION_TYPE';
    case COMMAND_VALIDATION_FAILED = 'ZBX_COMMAND_VALIDATION_FAILED';
    case INVALID_INPUT = 'ZBX_INVALID_INPUT';
    case UNKNOWN_ERROR = 'ZBX_UNKNOWN_ERROR';
}