<?php

define('AZURE_OPENAI_KEY', $_ENV['AZURE_OPENAI_KEY'] ?? null);
define('AZURE_OPENAI_MODEL', $_ENV['AZURE_OPENAI_MODEL'] ?? null);
define('AZURE_OPENAI_API_VERSION', $_ENV['AZURE_OPENAI_API_VERSION'] ?? null);
define('AZURE_OPENAI_BASE_URL', $_ENV['AZURE_OPENAI_BASE_URL'] ?? null);
define('AZURE_OPENAI_RESOURCE_NAME', $_ENV['AZURE_OPENAI_RESOURCE_NAME'] ?? null);
define('AZURE_OPENAI_EMBEDDINGS_MODEL', $_ENV['AZURE_OPENAI_EMBEDDINGS_MODEL'] ?? null);
define('AZURE_OPENAI_EMBEDDINGS_API_VERSION', $_ENV['AZURE_OPENAI_EMBEDDINGS_API_VERSION'] ?? null);

define('SERVICENOW_INSTANCE_NAME', $_ENV['SERVICENOW_INSTANCE_NAME'] ?? null);
define('SERVICENOW_INSTANCE_CUSTOM_URL', $_ENV['SERVICENOW_INSTANCE_CUSTOM_URL'] ?? null);
define('SERVICENOW_INSTANCE_USER', $_ENV['SERVICENOW_INSTANCE_USER'] ?? null);
define('SERVICENOW_INSTANCE_PASSWORD', $_ENV['SERVICENOW_INSTANCE_PASSWORD'] ?? null);

define('PROXY', $_ENV['PROXY'] ?? null);

define('ZABBIX_ENDPOINT', $_ENV['ZABBIX_ENDPOINT'] ?? null);
define('ZABBIX_USER', $_ENV['ZABBIX_USER'] ?? null);
define('ZABBIX_PASSWORD', $_ENV['ZABBIX_PASSWORD'] ?? null);
define('ZABBIX_EXECUTION_TYPE', $_ENV['ZABBIX_EXECUTION_TYPE'] ?? 0);